### ISSUE TITLE
Add Umbrella JS and Picnic CSS?

### ISSUE THREAD

**Issue by franciscop** [michaelrambeau/bestofjs-webui#16]
Those are two projects that I made, could they be added, please?

**Comment by michaelrambeau** [comment]
Hello, OK, I have just added the 2 projects. They will be available in the application web UI very soon (it takes 48 hours because there is an automatic process that checks stars on Github every day and I need 2 daily "screenshots" from Github to be able to show trends).

Remark: I think the project **description** should be easier to understand, well it should "**describe**" the project.

* [Umbrella JS](https://github.com/umbrellajs/umbrella) `Lightweight and intuitive javascript library`: a library to do what ?
* [Picnic CSS](https://github.com/picnicss/picnic) `Unpack your meal and start coding`: that does not describe the project at all, maybe you could say "A CSS toolkit to unpack your meal and start coding", do you know what I mean ?

It is just my opinion, you know better than me what describes your projects ;)

Thank you for your interest, I will call you back when it is online, be patient :)

**Comment by michaelrambeau** [comment]
Hello Francisco,
I am happy to tell you that your 2 projects are now available in http://bestof.js.org/ !
I hope it will make you happy too ;)

Tags:
* Picnic CSS => `CSS toolkit`
* Umbrella JS => `DOM manipulation` & `Utils`

Thank you for your attention, spread the word about bestof.js.org... or star the Github repo at least, this is all I request ;)

![image](https://cloud.githubusercontent.com/assets/5546996/15450932/f5273984-1fe6-11e6-95e4-ba82f2877bae.png)

**Comment by michaelrambeau** [comment]
Hello @franciscop ,
I am closing the request, since your 2 projects are included in the application as you can see here:
http://bestof.js.org/search/picnic
I'd love to hear some feedback from you Francisco.  
¡Por favor! :smiley:

**Comment by franciscop** [comment]
Hey sorry for not answering before, I totally agree I should change the tag line at least of Picnic CSS. This is a really cool project, why doesn't it have more stars? Did you publish it in HN, Reddit, etc?

**Comment by michaelrambeau** [comment]
Thank you for your comment.
Actually I published it 2 weeks ago:
* Reddit => https://redd.it/4k65fo
* Hacker News => https://news.ycombinator.com/item?id=11736505

But I cannot find it if I do a search on Reddit, I don't know why, I may have been missed something.
On HN, I can find the project if I do a search but it seems that no one else found it!

Let me know if you know the "right" way to publish.
I am working on some updates to improve the app (get rid of database ids for projects for example), I will try to publish again maybe.

**Comment by franciscop** [comment]
I have no idea about the "right" way to publish, officially it's just publish it and let the people vote and unofficially there are [other ways](http://alexstechthoughts.com/post/29406022580/how-to-get-on-the-frontpage-of-hacker-news). I've just followed the official route and got lucky (mainly with both of the projects I comment here).

**Comment by michaelrambeau** [comment]
Thank you for the tips, maybe it's just a question of "karma", I think you have a great karma 😉  !

**Comment by michaelrambeau** [comment]
@franciscop Today, PicnicCSS is the project number 1!

174 stars in one day... congratulations! :tada: 

![image](https://cloud.githubusercontent.com/assets/5546996/15874724/7b8d2c30-2d3f-11e6-9b1d-39ae5ac55b5a.png)

**Comment by franciscop** [comment]
Wow thanks! It was yesterday-today on the front page of Hacker News so I guess that should be it :)

**Comment by franciscop** [comment]
Also I changed the description following your recommeneation

**Comment by michaelrambeau** [comment]
:+1:  Good job!

**Comment by michaelrambeau** [comment]
Hello Francisco,
Just to tell you that I added a form to request new projects (see this issue for more details https://github.com/michaelrambeau/bestofjs-webui/issues/22).
Also, I added something to display the package "quality", using data from http://packagequality.com/.

![image](https://cloud.githubusercontent.com/assets/5546996/16543803/d178ecd4-4125-11e6-92ba-ca311d6267e7.png)

Let me know if these changes make sense for you, any feedback is welcome.
Thank you again for your support!
