### ISSUE TITLE
add flowtime.js under presentation engine

### ISSUE THREAD

**Issue by c0b** [michaelrambeau/bestofjs-webui#50]
https://github.com/marcolago/flowtime.js/

should be one of https://bestof.js.org/tags/presentation

**Comment by michaelrambeau** [comment]
Hello @c0b ,
Thank you for the suggestion!
Just in case, are you sure that the project is still actively maintained?
I am asking because the URL http://flowtime-js.marcolago.com/, mentionned after the project description, does not work for me, it's not a good sign usually.
Does it work for you?
Could you update the URL if it's one of your projects?
Thank you in advance!

**Comment by c0b** [comment]
the link in the README http://marcolago.github.io/flowtime.js/ works

also, the contributors graph https://github.com/marcolago/flowtime.js/graphs/contributors shows it's active since 2013 till present 2017, many commits

**Comment by michaelrambeau** [comment]
@c0b thank you very much for having checked the project activity.
It's too bad that the project main URL is wrong. 
As soon as you update (or make update) the project main URL, the project will be added to bestof.js.org.
Thank you for understanding!

**Comment by marcolago** [comment]
Thanks for letting me know about the problem.
The official link now is https://marcolago.github.io/flowtime.js/

**Comment by marcolago** [comment]
@michaelrambeau Thanks for the inclusion in your list.
I can confirm the project is still maintained.

**Comment by michaelrambeau** [comment]
@marcolago Thank you for the update, I will let you know when `flowtime.js` project is available on bestof.js.org.

**Comment by michaelrambeau** [comment]
Hello @marcolago and @c0b 
It's online, please check the `Presentation` tag: https://bestof.js.org/tags/presentation
Thank you for your feedback!
